### ISSUE TITLE
关于数据集的获取

### ISSUE THREAD

**Issue by Liulin1027** [palmchou/IsoGD-Baseline-Method#1]
数据集需要签个协议，怎么才能获取数据集

**Comment by palmchou** [comment]
Hi, 

You can find the details in http://www.cbsr.ia.ac.cn/users/jwan/database/isogd.html

Copied here also:

### Download Instructions

To obtain the database, please follow the steps below:

1. Download and print the document [Agreement](http://www.cbsr.ia.ac.cn/users/jwan/database/Chalearn_LAP-IsoGD_agreement.txt) for using Chalearn LAP IsoGD
1. Sign the agreement
1. Send the agreement to jun.wan@ia.ac.cn
1. Check your email to find a login account and a password of our website after one day, if your application has been approved.
1. Download the Chalearn LAP IsoGD database from our website with the authorized account within 48 hours.
```
